### ISSUE TITLE
DLine needs work

### ISSUE THREAD

**Issue by cablio** [cablio/cs151hw6#13]
DLine is just insane. 
Knobs for DLine should depend on the starting point of the line, maybe even have two extra Knob subclasses - Left and Right.
Possibly implement DLine with two Points instead.

**Comment by davisjake** [comment]
Fixed some of the line issue

**Comment by davisjake** [comment]
Added a way to fix movement of line completely, but now there is errors when trying to reselect the line.

**Comment by davisjake** [comment]
fixed
